introduce failing ci step
Signed-off-by: Andy Sadler <ansadler@redhat.com>

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -17,4 +17,6 @@ jobs:
 
           sleep 30
 
-          echo "Done!"
+          echo "Failed!"
+
+          exit 1
